apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barbican-proxy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: barbican-proxy

  source:
    repoURL: "https://github.com/Mobility-Scooter-Project/mobility-scooter-infra.git"
    targetRevision: main
    path: charts/api
    helm:
      values: |
        nameOverride: barbican-proxy
        fullnameOverride: barbican-proxy

        image:
          repository: ghcr.io/mobility-scooter-project/barbican-proxy
          tag: sarina-development
          pullPolicy: IfNotPresent

        replicas: 1

        service:
          port: 8080
          targetPort: 8080
        containerPort: 8080

        env:
          - name: OS_AUTH_URL
            value: "https://js2.jetstream-cloud.org:5000/v3/"
          - name: BARBICAN_URL
            value: "https://js2.jetstream-cloud.org:9311"
          - name: KV_URL
            value: "redis://kv.barbican-proxy.svc.cluster.local:6379"

        kv:
          enabled: true
          connectionStringEnvVarName: KV_URL

        database:
          enabled: false
        queue:
          enabled: false

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        ingress:
          enabled: false

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true