apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-proxy-config
  namespace: barbican-proxy
data:
  OS_APPLICATION_CREDENTIAL_CLIENT_ID: "a017bf17b9ab4a8097ef311eb3defd63"
  OS_APPLICATION_CREDENTIAL_CLIENT_SECRET: "fmApR5i62JNZYH_vp41oRwPPaYIeUOBDKEFOP3NlRfLltYgSqHNZPxI7BcV0HWGyRzbglurhdpNfngCOgcTjuw"
  OS_AUTH_URL: "https://js2.jetstream-cloud.org:5000/v3/"
  BARBICAN_URL: "https://js2.jetstream-cloud.org:9311"
  KV_URL: "redis://redis-service.barbican-proxy.svc.cluster.local:6379"  # Point to Redis service in cluster